language: ruby
rvm:
- 2.5
env:
  global:
  - JEKYLL_ENV=production
  - secure: Sa6LOginTeDQNA0qld+KCu9FkRYP2JG8pWS08mDMZ5k4QxkGQHyniSiM/A/Hg5jqQsri3EEbLTgxal+XKLfvxYuRn9h0h17MzbGTvB2mcbvdnL90bLeWKFGYyqziJOuiHmlCzg0OaLFwg52OihxPOysPXCCZ0sp4DlK9yjpbH0BKD/J9b7I1IXOErhhZPAFthxn6Wh2S5TBuYqpVu1X1TdOKAKI/GYONknp4ESyqEXU5KQT9dtkhONOtcBHt8NgqR4q4mo5ILtYQLwr/W/77QIz6EJ6zzQWByqJBODJDclBQ6G/LDnLCy64CoM/l/DGk0Ksntqn8cYHTRiIB/V2rp8mgKPqEQQ2gItMzPFwEzsXDPNg9qFWQTSNJOMUM30FcxCkp81+o4mFG+yzMn/eF9S6Bx/7tDVCSlm0xEkuFv/pWCXtjVTSMe2mPBDqX0wG2otGil7wp5dKl2V8GnAnzSdb08haUD6CXWfC7sfBs3QudpV6krZovGzqblRoRqG8xpMUowOYzyjBK3wWNNAF1ZUApX1V/JHQHirWcPoIbe0mY2MmQ6xmO8hskeGoWJm6nrljW95U4ouxFheVfML/VeBMI5n9q5+zAscCXmjoM+PYih8N6/7SvSZKyC70aC7svSFjEcGGdj1sksGEdOyIi/grw1erc0QjjkFQKFu76src=
  - secure: PztS+tkL/jsRySl+y4YRZY1SDfXRgWsjQwbUW+oiKB7Lt1K7Figxa8bzlK21EssjOw1peoX7uLtBY37AJ2f6bD52kt5GmT5Vp4osuA/ko6NY8h0PdSlF2AmpK0nZddqOrnuh1YpV2hapn8uHXsSz6RceADsKUKBV20Mwes6X6583+DnVTNJywpvv8w3vRyefUlzjRn2+GIDmyemE898wZEpDvTAzhkEU+qlwAOP6TjT7t4bmrsXKuuCAozUwhA7bHiOEoEshFynUCLALZ6BrMOtcmDONWdgJwNlRGn9d+8WJl/1cwF1BeVztC0oLmgWaDncGM9oLCrdtssweMCfLT+9CdiGv7loifzXG+vuRPt11wmHp2i3dPplwglhFMKeThI26nKM/ooHbLKWp2HwjTGdPtXdPugXhKmAqY6lUm9MUdku5Y9szbSH/fHhc570EnvxMgJnHMe6n+30hrZXCZGqKEZjNJUq5KURd0/KvJmLDqZIlmo0c87vBaWCfKZ5WYin/vjN18HNvzqrAI4lFMZq2ZHtEVxt+ApYwDE621Xm7yWhVubgr5xM+CJXC471jOjzXpW+prUC/dr1mDM3OfNGCxEFz5n1rNTtcgoT8Yp+bgWpdmX9Rrn4j5Y4tKcywxsDG4rh8oTp+pAC7T+A1Qya257p0Qw1jX9jP+P8aMRM=
  - secure: gc5pIWAi/topa/ca2vUsCJKI1GsyJHhpgm3dr5x+Lthf6dvTXSLpcKW7r3AHvqofgrACzqI35FOtZv9/ggHfKZfB++CGHjC/vfEGrd9jDEYFbBPuEkxh8kM7skm/SxuARpXMCJ0UVjDwvL0hLPfrU6ys4b6reF9KMRlDKjz5NRd031FCD69IqVIACYPRr0B2MJURJLVhSn5ySQmXlL9e83uVjy0EYwRDI3cv1usVoBWaNa8gJOvWLZCOUVMbZyO6JiSI5YnvpN8A4LhStIW8ct2GCixMxDHsaxgYSWU9nlCpYd2uwBlsiha1B6mQ+nXQtB5jtZ/r7JO29pBCOegIZ386I3unk/6KIHgszyUKY/gybj9KpisXSj/rpPTY3iUxbKO/2zG2ZEKKRZtnUlqTdfg6oPsBW648j5McQ+FJLXMu6lsoywxnHOEbEgbpnSFTtP4Lyti8vN8lDxr9i21u5OcZ00YKO4+PSFKECWEksyB7z14nI60Gzqp4insjThSO2S7USqyIA7AFOhGKqnquCAZPjX+eOo2ISwyjzfmJnvTHySZumqoU5MZZDjobXI9dC1eEDYweXhm1/alx96fMViKvjince5AcenPJjnrR13Y8BZNGQrZqjYNJ83xi5IzZoICxVvBB2PYsLykP0b98AGQzSKqR5cRZncCf4Zf6nrk=
branches:
  only:
  - gh-pages
script:
- bundle exec jekyll build
before_deploy:
- openssl aes-256-cbc -K $encrypted_d15196a1bbe0_key -iv $encrypted_d15196a1bbe0_iv
  -in deploy_rsa.enc -out /home/deploy/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy\_rsa
- ssh-add /tmp/deploy\_rsa
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after _site/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: gh-pages
